//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MFMLAP;Initial Catalog=SBOAffinity;User Id = sa; Password = super;")]
        public string SapConString {
            get {
                return ((string)(this["SapConString"]));
            }
            set {
                this["SapConString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MFMLAP;Initial Catalog=HCMOneAffinity;User Id = sa; Password = super;" +
            "")]
        public string PayrollConString {
            get {
                return ((string)(this["PayrollConString"]));
            }
            set {
                this["PayrollConString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120000")]
        public int EmployeeTimer {
            get {
                return ((int)(this["EmployeeTimer"]));
            }
            set {
                this["EmployeeTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rNUZOXBMfW067CBbf1GasiTYYNdQNqt4XxzBHJ4WUnd6xRfPJ8IcutiS33bsMBd7bLuvoCHdfSjD90Y3o" +
            "ceRVS/V6Z2bE94guiAKmSdJXG7BrZ+JRw5BZTB99/ZG7oJL1yCy46qJXjUp9Fv6iR9stEl0K+xQkiBro" +
            "MwwaH9zDS8=")]
        public string LicenseKey {
            get {
                return ((string)(this["LicenseKey"]));
            }
            set {
                this["LicenseKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("86400000")]
        public int EmployeeFSTimer {
            get {
                return ((int)(this["EmployeeFSTimer"]));
            }
            set {
                this["EmployeeFSTimer"] = value;
            }
        }
    }
}
